### ISSUE TITLE
May I ask your python version?

### ISSUE THREAD

**Issue by lilinghui111** [samson-wang/cython_bbox#1]
Thank you for your work.May I ask your python version and envs?
I had this problem:"cl.exe failed with exit status2".
Thank you!!!!!!

**Comment by samson-wang** [comment]
Emm `cl.exe`.
Do you run this on Windows? I only tested it on Linux and Mac. And I have no Windows machine to debug with it.
Sorry.

**Comment by samson-wang** [comment]
You can compile it manually. The compiler will give much more information.
