### ISSUE TITLE
why it states +1 in the end?

### ISSUE THREAD

**Issue by IgorDavidyuk** [samson-wang/cython_bbox#2]
https://github.com/samson-wang/cython_bbox/blob/4a432fe35814cd5eb6590bab431e43ae3664c395/src/cython_bbox.pyx#L35

**Comment by IgorDavidyuk** [comment]
As I understand it works approximately good with large boxes (>100px)

**Comment by samson-wang** [comment]
Given a box (0,0,5,5). The pixels of width is `(5 - 0 + 1) = 6`

**Comment by samson-wang** [comment]
A bit different from the `length` of a line in geometry. In Detectron2 the computation of area/length changed.

For large box the difference of the two computations is negligible.

**Comment by IgorDavidyuk** [comment]
> A bit different from the `length` of a line in geometry. In Detectron2 the computation of area/length changed.
> 
> For large box the difference of the two computations is negligible.

I got it, you are right. 
Thank you!

**Comment by mrtj** [comment]
On the other hand, it is nowhere stated that this code works only with pixel-based coordinate system. My code uses coordinates normalized to the (1; 0) interval (in relation to the image width and height), and of course adding a casual 1 to the coordinates completely messes up the area being calculated. 

(In my code, this library is buried under 2-3 layers of other libraries that I do not own, so to debug this `+1` error took me several days)
