### ISSUE TITLE
won't build on ubuntu with windows-friendly change to setup.py

### ISSUE THREAD

**Issue by commonloon** [samson-wang/cython_bbox#4]
I had to revert to extra_compile_args=['-Wno-cpp'] in setup.py

The version of setuptools in my Anaconda distribution will only accept a list as the value of extra_compile_args, whereas the most recent setup.py (6eb3ff2) has a dict.

**Comment by samson-wang** [comment]
https://github.com/samson-wang/cython_bbox/commit/a36abfa456ef6d5e7a5363abe280b24f5f30e6ad
